"""Emit library.txt (+ build metadata) for the generated procgen package.

For every enabled manifest asset whose OBJ variants exist on disk, writes one
``EXPORT`` line per physical variant under the SAME virtual path -- X-Plane
picks a physical object at random per placement, which is the library's
visual-diversity mechanism, while the building-overlay pool sees a single
dimension-exact entry (it unions the variants' identical bounds).

Run:  python build_procgen_library.py --output <pkg>
"""

from __future__ import annotations

import argparse
import datetime as _dt
import json
import os
import sys

HERE = os.path.dirname(os.path.abspath(__file__))

HEADER = """A
800
LIBRARY

# O4SFR ProcGen Library -- procedurally generated building objects.
# Generated by scripts/asset_pipeline/procgen/ (Ortho4XP-SegFormer).
# Textures composite AI-generated photo sources per (region x class
# group) combo; geometry is parametric. License: CC0.
# DO NOT EDIT: regenerate via build_procgen_library.py.
"""


def main(argv=None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--manifest", default=os.path.join(HERE, "procgen_manifest.json")
    )
    parser.add_argument("--output", required=True,
                        help="Library package folder (Custom Scenery).")
    parser.add_argument("--allow-missing", action="store_true",
                        help="Skip variants whose OBJ is missing instead of "
                             "failing (useful for partial test builds).")
    args = parser.parse_args(argv)

    with open(args.manifest, "r", encoding="utf-8") as fh:
        manifest = json.load(fh)

    lines = []
    exported_paths = 0
    exported_objs = 0
    missing = []
    for asset in manifest["assets"]:
        if not asset.get("enabled"):
            continue
        variant_lines = []
        for variant in asset["variants"]:
            physical = variant["physical_path"]
            if not os.path.isfile(os.path.join(args.output, physical)):
                missing.append(physical)
                continue
            variant_lines.append(
                f"EXPORT {asset['virtual_path']} {physical}"
            )
        if variant_lines:
            lines.extend(variant_lines)
            exported_paths += 1
            exported_objs += len(variant_lines)

    if missing and not args.allow_missing:
        for physical in missing[:10]:
            print(f"  ! missing OBJ: {physical}")
        raise SystemExit(
            f"{len(missing)} manifest OBJs missing under {args.output}; "
            f"run generate_procedural_buildings.py first or pass "
            f"--allow-missing for a partial library"
        )

    library_txt = os.path.join(args.output, "library.txt")
    with open(library_txt, "w", encoding="utf-8", newline="\n") as fh:
        fh.write(HEADER)
        fh.write("\n")
        fh.write("\n".join(lines))
        fh.write("\n")

    build_info = {
        "built_utc": _dt.datetime.now(_dt.timezone.utc).isoformat(
            timespec="seconds"
        ),
        "lib_version": manifest["lib_version"],
        "config_sha1": manifest["config_sha1"],
        "virtual_paths": exported_paths,
        "obj_files": exported_objs,
        "missing_objs": len(missing),
    }
    with open(os.path.join(args.output, "build_info.json"), "w",
              encoding="utf-8", newline="\n") as fh:
        json.dump(build_info, fh, indent=1, sort_keys=True)
        fh.write("\n")

    print(
        f"library.txt: {exported_paths} virtual paths, {exported_objs} "
        f"EXPORT lines ({len(missing)} missing skipped)"
    )
    return 0


if __name__ == "__main__":
    sys.exit(main())
