"""Composite AI-generated photo sources into the per-combo atlas layouts.

THE shipping texture path (July 2026 overhaul): all visible albedo pixels
come from PNGs in codex_realistic/sources (generated by codex-cli's image
tool -- codex generates images ONLY; this compositor owns every other
pixel decision).  One atlas per (region flavor x class group) combo per
page: crops, tiles, rescales, recolors, seam-fixes and lays the photo
sources into the combo's own strip bands from atlas_layout.json, then
paints the gloss mask and emits the companion normal map.

Source lookup chain per material/sprite base name:
    <base>__<flavor>__<group>.png  >  <base>__<flavor>.png  >  <base>.png

Compositor rules inherited from the first codex round (hard-won):
  * NO cross-fade seam blends -- ghosting reads as pale bands; mirror-tile
    with divisor-snapped repeat counts instead.
  * aspect-true material spans (no horizontal stretch).
  * flat-field illumination correction on every tiled photo.
  * row-chroma stabilization BEFORE sprite pasting.
  * golden-ratio stagger only for materials without vertical structure.

Run:  python compose_atlases.py --output <pkg> [--combos asia/apt,...]
"""

from __future__ import annotations

import argparse
import hashlib
import json
import random
import sys
from pathlib import Path

import numpy as np
from PIL import Image, ImageDraw, ImageFilter

HERE = Path(__file__).resolve().parent
if str(HERE) not in sys.path:
    sys.path.insert(0, str(HERE))

import atlas  # noqa: E402
from atlas import FLAVORS, GROUPS, combo_key  # noqa: E402
from archetypes.combo_styles import CLEAN_FLAVORS  # noqa: E402

DEFAULT_SOURCES = HERE / "codex_realistic" / "sources"
NML_SIZE = 2048

# Shared bases that MUST exist (the original photo set); regional and
# group-specific bases upgrade the look as codex generates them but never
# block a compose run.
REQUIRED_SHARED = (
    "brick_wall.png", "siding_wall.png", "stucco_wall.png",
    "concrete_wall.png", "roof_shingle.png", "roof_tile.png",
    "roof_metal.png", "roof_flat.png", "trim_wood.png", "grunge.png",
    "window_plain.png", "window_sash.png", "window_shuttered.png",
    "window_slider.png", "door_panel.png", "door_plank.png",
    "door_flush.png", "storefront.png", "roller_door.png",
)

# family -> source base; per-(group, family) overrides refine it.
MATERIAL_SOURCES = {
    "brick": "brick_wall", "siding": "siding_wall", "stucco": "stucco_wall",
    "concrete": "concrete_wall", "panel": "panel_wall",
    "metal": "metal_wall", "curtain": "curtain_wall",
    "roof_shingle": "roof_shingle", "roof_tile": "roof_tile",
    "roof_metal": "roof_metal", "roof_flat": "roof_flat",
    "trim": "trim_wood",
}
GROUP_MATERIAL_OVERRIDES = {
    # Tilt-up panels read better than generic stained concrete on big sheds.
    ("ind", "concrete"): ("tiltup_wall", "concrete_wall"),
}
# Fallback chain when a group-specific base has no photo yet.
MATERIAL_FALLBACKS = {
    "panel_wall": ("concrete_wall",),
    "metal_wall": ("roof_metal",),
    "curtain_wall": ("concrete_wall",),
    "tiltup_wall": ("concrete_wall",),
    "mosaic_wall": ("stucco_wall",),
}

# World HEIGHT (m) one source photo spans; width follows the photo's own
# aspect ratio so the material is never stretched.
SOURCE_SPAN_Y_M = {
    "brick_wall": 1.2,       # ~16 courses of 7.5 cm
    "siding_wall": 2.0,      # ~10 laps of 20 cm
    "stucco_wall": 3.2,
    "concrete_wall": 3.2,
    "panel_wall": 5.8,       # ~2 prefab storeys per photo
    "mosaic_wall": 2.2,
    "metal_wall": 2.6,
    "curtain_wall": 3.2,     # ~1 glazing storey (2 pane rows) per cell
    "tiltup_wall": 6.0,
    "roof_shingle": 2.8,
    "roof_tile": 3.8,
    "roof_metal": 2.6,
    "roof_flat": 8.0,
    "trim_wood": 0.3,
}

MATERIAL_CONTRAST = {
    "brick_wall": 0.78, "siding_wall": 0.62, "stucco_wall": 0.55,
    "concrete_wall": 0.58, "panel_wall": 0.58, "mosaic_wall": 0.55,
    "metal_wall": 0.50, "curtain_wall": 0.60, "tiltup_wall": 0.55,
    "roof_shingle": 0.52, "roof_tile": 0.62, "roof_metal": 0.50,
    "roof_flat": 0.48, "trim_wood": 0.55,
}

# Materials whose vertical repeats may be staggered horizontally (breaks
# course-band periodicity); materials with continuous vertical structure
# (ribs, pans, mullions, panel joints) must keep repeats aligned.
SHIFT_REPEATS = {
    "brick_wall": True, "siding_wall": True, "stucco_wall": True,
    "roof_shingle": True, "roof_flat": True, "tiltup_wall": True,
    "roof_tile": False, "roof_metal": False, "concrete_wall": False,
    "panel_wall": False, "mosaic_wall": False, "metal_wall": False,
    "curtain_wall": False, "trim_wood": False,
}

REGIONAL_MEAN_SHIFT = 0.30   # how far regional photos move toward palette
SPRITE_SOFTEN = 0.70         # contrast multiplier for window/door sprites

# Dark glass panes (user directive 2026-07-08): every glazing surface gets
# a deterministic dark overlay tinted from the region's glass palette --
# kills the sky/cloud reflections baked into the AI window sprites and
# curtain-wall photos while keeping frames/mullions readable underneath.
GLASS_DARK_FACTOR = 0.42     # pane brightness relative to palette glass
GLASS_OVERLAY_ALPHA = 150    # wall/ground window panes
CURTAIN_OVERLAY_ALPHA = 120  # curtain-wall glazing fields
STOREFRONT_OVERLAY_ALPHA = 110
LOBBY_OVERLAY_ALPHA = 95
HIGHBAND_OVERLAY_ALPHA = 115

# On-disk optimization: adaptive-palette PNGs keep the full 4096 res at
# ~1-2 MB per page (vs 6-13 MB truecolor) with no visible loss at atlas
# texel density; X-Plane decodes indexed PNG like any other.
QUANT_COLORS = 256


def dark_glass_color(palette) -> tuple:
    g = palette.get("glass", (96, 112, 126))
    return tuple(int(round(c * GLASS_DARK_FACTOR)) for c in g)


def darken_glass(albedo, box, color, alpha):
    x0, y0, x1, y1 = (int(round(v)) for v in box)
    if x1 <= x0 or y1 <= y0:
        return
    overlay = Image.new("RGBA", (x1 - x0, y1 - y0),
                        (color[0], color[1], color[2], int(alpha)))
    albedo.alpha_composite(overlay, (x0, y0))

# Per-flavor dirt handling.  CLEAN_FLAVORS (combo_styles) get the grunge
# overlay disabled outright in compose_page; stain_lift additionally
# scrubs staining baked into the AI source photos themselves (asia photos
# were originally generated with heavy weathering — the 4th and final
# grime source).  USER DIRECTIVE 2026-07-08: asia stays clean.
FLAVOR_DIRT = {
    "asia": {"stain_lift": {"stucco_wall": 0.8, "concrete_wall": 0.8,
                            "brick_wall": 0.6, "panel_wall": 0.8,
                            "mosaic_wall": 0.7, "metal_wall": 0.6,
                            "curtain_wall": 0.4, "tiltup_wall": 0.8},
             "grunge_scale": 0.0},
}

SPRITE_BASES = (
    "window_plain", "window_sash", "window_shuttered", "window_slider",
    "window_barred", "window_arched", "window_apt", "window_office",
    "window_ind", "door_panel", "door_plank", "door_flush", "door_home",
    "storefront", "roller_door", "dock_door", "ac_unit", "entrance_apt",
    "balcony_rail",
)


def stable_u32(*parts: object) -> int:
    data = "|".join(str(p) for p in parts).encode("utf-8")
    return int.from_bytes(hashlib.blake2b(data, digest_size=4).digest(),
                          "little")


def np_rgb(img: Image.Image) -> np.ndarray:
    return np.asarray(img.convert("RGB"), dtype=np.float32)


def palette_color(palette: dict, key: str, shade: int = 0):
    val = palette[key]
    if isinstance(val[0], int):
        return tuple(int(x) for x in val)
    return tuple(int(x) for x in val[min(shade, len(val) - 1)])


def avg_color(*colors):
    arr = np.asarray(colors, dtype=np.float32)
    return tuple(int(round(x)) for x in arr.mean(axis=0))


def recolor_luma(arr, target, contrast, chroma_keep=0.08):
    """Full palette recolor: photo detail modulates the palette color."""
    arr = arr.astype(np.float32)
    target_arr = np.asarray(target, dtype=np.float32)
    luma = arr @ np.array([0.299, 0.587, 0.114], dtype=np.float32)
    detail = luma - float(luma.mean())
    chroma = arr - luma[..., None]
    out = (target_arr[None, None, :] + detail[..., None] * contrast
           + chroma * chroma_keep)
    return np.clip(out, 0, 255)


def mild_match(arr, target, strength=0.25):
    """Mean-shift toward the palette while keeping the photo's own hues."""
    arr = arr.astype(np.float32)
    target_arr = np.asarray(target, dtype=np.float32)
    mean = arr.reshape(-1, 3).mean(axis=0)
    shifted = arr + (target_arr - mean)[None, None, :] * strength
    return np.clip(shifted, 0, 255)


def reduce_stains(arr: np.ndarray, amount: float) -> np.ndarray:
    """Lift broad dark staining toward the mean without touching texture
    brighter than the mean."""
    luma = arr @ np.array([0.299, 0.587, 0.114], dtype=np.float32)
    dark = np.clip(float(luma.mean()) - luma, 0.0, None)
    return np.clip(arr + (dark * amount)[..., None], 0, 255)


def make_h_loop(img: Image.Image, seam_frac: float = 0.18) -> Image.Image:
    """Cross-blend a wide seam region so the tile wraps in U (grunge map
    only -- materials mirror-tile instead)."""
    arr = np_rgb(img)
    h, w, _ = arr.shape
    seam = max(8, min(w // 3, int(w * seam_frac)))
    left = arr[:, :seam].copy()
    right = arr[:, -seam:].copy()
    ramp = np.linspace(0.0, 1.0, seam, dtype=np.float32)[None, :, None]
    blended = right * (1.0 - ramp) + left * ramp
    arr[:, :seam] = blended
    arr[:, -seam:] = blended
    return Image.fromarray(np.uint8(np.rint(np.clip(arr, 0, 255))), "RGB")


def _smooth1d(v: np.ndarray, win: int) -> np.ndarray:
    win = max(3, win | 1)
    pad = win // 2
    vp = np.pad(v, pad, mode="reflect")
    kernel = np.ones(win, dtype=np.float32) / win
    return np.convolve(vp, kernel, mode="valid")


def flatten_field(arr: np.ndarray) -> np.ndarray:
    """Remove the photo's low-frequency illumination gradient (both axes);
    tiled every ~1-4 m it otherwise reads as broad luminance banding."""
    arr = arr.astype(np.float32)
    luma = arr @ np.array([0.299, 0.587, 0.114], dtype=np.float32)
    g = float(luma.mean())
    row = luma.mean(axis=1)
    corr_r = g - _smooth1d(row, max(5, arr.shape[0] // 6))
    arr = arr + corr_r[:, None, None]
    luma = arr @ np.array([0.299, 0.587, 0.114], dtype=np.float32)
    col = luma.mean(axis=0)
    corr_c = float(luma.mean()) - _smooth1d(col, max(5, arr.shape[1] // 6))
    arr = arr + corr_c[None, :, None]
    return np.clip(arr, 0, 255)


def _divisor_count(total: int, ideal_size: float, cap: int = 96) -> int:
    """Repeat count n (a divisor of total) whose tile size total/n is
    closest to ideal_size on a log scale."""
    import math
    best, best_err = 1, float("inf")
    for n in range(1, cap + 1):
        if total % n:
            continue
        err = abs(math.log((total / n) / max(1e-6, ideal_size)))
        if err < best_err:
            best, best_err = n, err
    return best


class Sources:
    """All PNGs in sources/, with the combo preference chain."""

    def __init__(self, src_dir: Path):
        missing = [n for n in REQUIRED_SHARED
                   if not (src_dir / n).is_file()]
        if missing:
            raise SystemExit("missing sources: " + ", ".join(missing))
        self.images: dict[str, Image.Image] = {}
        for p in sorted(src_dir.glob("*.png")):
            self.images[p.stem] = Image.open(p).convert("RGB")

    def lookup(self, base: str, flavor: str, group: str):
        """Returns (image, key, is_regional) or (None, None, False)."""
        for key, regional in ((f"{base}__{flavor}__{group}", True),
                              (f"{base}__{flavor}", True),
                              (base, False)):
            if key in self.images:
                return self.images[key], key, regional
        return None, None, False

    def get_material(self, base: str, flavor: str, group: str):
        """Material photo with fallback chain; returns (img, span_base,
        regional)."""
        img, _key, regional = self.lookup(base, flavor, group)
        if img is not None:
            return img, base, regional
        for fb in MATERIAL_FALLBACKS.get(base, ()):
            img, _key, regional = self.lookup(fb, flavor, group)
            if img is not None:
                return img, fb, regional
        raise KeyError(f"no source for material {base}")

    def has(self, base: str, flavor: str | None = None,
            group: str | None = None) -> bool:
        if flavor is not None:
            if group is not None and f"{base}__{flavor}__{group}" \
                    in self.images:
                return True
            if f"{base}__{flavor}" in self.images:
                return True
        return base in self.images


def tile_material(src, strip, span_base, size, target, rng, regional,
                  flavor="generic"):
    """Mirror-tile one photo across a strip band, palette-matched."""
    h = int(strip["px"][1] - strip["px"][0])
    w = size
    gutter = max(1, int(round(atlas.GUTTER_PX * (size / 2048.0))))
    px_m_x = w / float(strip["world_w_m"])
    px_m_y = (h - 2 * gutter) / float(strip["world_h_m"])
    span_y = SOURCE_SPAN_Y_M[span_base]
    span_x = span_y * (src.width / float(src.height))  # aspect-true
    n_x = _divisor_count(w, span_x * px_m_x)
    n_y = _divisor_count(h, span_y * px_m_y, cap=16)
    tile_w = w // n_x
    tile_h = h // n_y
    tile = src.resize((tile_w, tile_h), Image.Resampling.BOX)
    arr = flatten_field(np_rgb(tile))
    if regional:
        arr = mild_match(arr, target, REGIONAL_MEAN_SHIFT)
    else:
        arr = recolor_luma(arr, target, MATERIAL_CONTRAST[span_base])
    lift = (FLAVOR_DIRT.get(flavor) or {}).get("stain_lift", {})
    if span_base in lift:
        arr = reduce_stains(arr, float(lift[span_base]))
    off_x = rng.randrange(tile_w)
    band = np.empty((h, w, 3), dtype=np.float32)
    stagger = SHIFT_REPEATS.get(span_base, False)

    def mirror_idx(vals, n):
        p = vals % (2 * n)
        return np.where(p < n, p, 2 * n - 1 - p)

    for k in range((h + tile_h - 1) // tile_h):
        rows0 = k * tile_h
        rows1 = min(h, rows0 + tile_h)
        src_rows = np.arange(rows0, rows1, dtype=np.int32)
        y_idx = mirror_idx(src_rows, tile_h)
        shift = (off_x + (int(round(k * tile_w * 0.6180339))
                          if stagger else 0))
        if n_x >= 2:
            x_idx = mirror_idx(np.arange(w, dtype=np.int32) + shift, tile_w)
        else:
            x_idx = (np.arange(w, dtype=np.int32) + shift) % tile_w
        band[rows0:rows1] = arr[y_idx[:, None], x_idx[None, :]]
    return np.clip(band, 0, 255)


def apply_unit_banding(band, strip, family, palette, pattern, rng,
                       regional, size):
    if family not in ("stucco", "concrete", "panel"):
        return band
    if rng.random() >= float(pattern.get("unit_banding", 0.0)):
        return band
    pool = palette.get("unit_pool")
    if not pool:
        return band
    n = max(2, int(round(float(strip["world_w_m"])
                         / float(pattern.get("unit_w_m", 5.0)))))
    edges = [int(round(i * size / n)) for i in range(n + 1)]
    out = band.copy()
    for i in range(n):
        xa, xb = edges[i], edges[i + 1]
        target = tuple(int(v) for v in rng.choice(pool))
        strength = 0.5 if regional else 0.45
        if regional:
            out[:, xa:xb] = mild_match(out[:, xa:xb], target, strength)
        else:
            out[:, xa:xb] = recolor_luma(out[:, xa:xb], target, 0.45, 0.04)
        bw = min(6, max(1, xb - xa))
        out[:, xa:xa + bw] = np.clip(out[:, xa:xa + bw] * 1.05 + 5, 0, 255)
    return out


def apply_grunge(band, grunge, strength, rng):
    if strength <= 0:
        return band
    h, w, _ = band.shape
    g = make_h_loop(grunge.convert("RGB")).convert("L").resize(
        (w, h), Image.Resampling.BOX)
    if rng.random() < 0.5:
        g = g.transpose(Image.Transpose.FLIP_LEFT_RIGHT)
    garr = np.asarray(g, dtype=np.float32) / 255.0
    row_mean = garr.mean(axis=1)
    garr = np.clip(garr - (row_mean - float(garr.mean()))[:, None], 0, 1)
    factor = 1.0 - strength * np.clip(0.62 - garr, 0.0, 0.62)[..., None]
    return np.clip(band * factor, 0, 255)


def crop_sprite(img: Image.Image, threshold: float = 25.0) -> Image.Image:
    arr = np.asarray(img.convert("RGB"), dtype=np.float32)
    border = np.concatenate([arr[:20].reshape(-1, 3),
                             arr[-20:].reshape(-1, 3),
                             arr[:, :20].reshape(-1, 3),
                             arr[:, -20:].reshape(-1, 3)], axis=0)
    bg = np.median(border, axis=0)
    diff = np.sqrt(((arr - bg[None, None, :]) ** 2).sum(axis=2))
    mask = diff > threshold
    ys, xs = np.where(mask)
    if len(xs) == 0:
        return img.convert("RGBA")
    pad = 5
    x0, x1 = max(0, xs.min() - pad), min(img.width, xs.max() + 1 + pad)
    y0, y1 = max(0, ys.min() - pad), min(img.height, ys.max() + 1 + pad)
    rgb = arr[y0:y1, x0:x1]
    d = diff[y0:y1, x0:x1]
    alpha = np.clip((d - threshold * 0.55) / (threshold * 1.35), 0, 1) * 255.0
    solid = alpha > 90
    idx = np.arange(solid.shape[0])[:, None]
    has = solid.any(axis=0)
    first = np.where(has, np.argmax(solid, axis=0), solid.shape[0])
    last = np.where(has,
                    solid.shape[0] - 1 - np.argmax(solid[::-1], axis=0), -1)
    filled = (idx >= first[None, :]) & (idx <= last[None, :])
    er = filled.copy()
    er[1:] &= filled[:-1]; er[:-1] &= filled[1:]
    er[:, 1:] &= filled[:, :-1]; er[:, :-1] &= filled[:, 1:]
    alpha = np.maximum(alpha, er * 255.0)
    alpha = Image.fromarray(np.uint8(np.rint(alpha)), "L").filter(
        ImageFilter.GaussianBlur(0.45))
    rgba = Image.fromarray(np.uint8(np.rint(np.clip(rgb, 0, 255))),
                           "RGB").convert("RGBA")
    rgba.putalpha(alpha)
    return rgba


def soften(arr: np.ndarray, factor: float) -> np.ndarray:
    mean = arr.reshape(-1, arr.shape[-1]).mean(axis=0)
    return np.clip(mean[None, None, :] + (arr - mean[None, None, :]) * factor,
                   0, 255)


def paste_sprite(canvas, sprite, box, tint=None, strength=0.22,
                 soften_factor=1.0):
    x0, y0, x1, y1 = (int(round(v)) for v in box)
    if x1 <= x0 or y1 <= y0:
        return
    spr = sprite.resize((max(2, x1 - x0), max(2, y1 - y0)),
                        Image.Resampling.LANCZOS)
    arr = np.asarray(spr.convert("RGBA"), dtype=np.float32)
    if soften_factor < 1.0:
        arr[..., :3] = soften(arr[..., :3], soften_factor)
    if tint is not None:
        arr[..., :3] = mild_match(arr[..., :3], tint, strength)
    spr = Image.fromarray(np.uint8(np.rint(np.clip(arr, 0, 255))), "RGBA")
    canvas.alpha_composite(spr, (x0, y0))


def build_sprites(sources: Sources) -> dict:
    """(base, flavor, group) -> cropped RGBA sprite via the chain."""
    out = {}
    crop_cache = {}
    for base in SPRITE_BASES:
        for flavor in FLAVORS:
            for group in GROUPS:
                img, key, _regional = sources.lookup(base, flavor, group)
                if img is None:
                    continue
                if key not in crop_cache:
                    crop_cache[key] = crop_sprite(img)
                out[(base, flavor, group)] = crop_cache[key]
    return out


def window_sprite_base(pattern, flavor, group, sprites):
    """Regional/group window sprite selection."""
    if group == "apt" and ("window_apt", flavor, group) in sprites:
        return "window_apt"
    if group == "ind" and ("window_ind", flavor, group) in sprites:
        return "window_ind"
    if pattern.get("arch") and ("window_arched", flavor, group) in sprites:
        return "window_arched"
    if (float(pattern.get("bars_prob", 0.0)) >= 0.5
            and ("window_barred", flavor, group) in sprites):
        return "window_barred"
    if pattern.get("shutters"):
        return "window_shuttered"
    mullion = pattern.get("mullion", "single")
    if mullion == "sash":
        return "window_sash"
    if mullion == "slider":
        return "window_slider"
    return "window_plain"


def door_sprite_base(pattern, flavor, group, sprites):
    if group == "res" and ("door_home", flavor, group) in sprites:
        return "door_home"
    style = pattern.get("door_panels", "panel2x2")
    if style == "planks":
        return "door_plank"
    if style == "flush":
        return "door_flush"
    return "door_panel"


def add_gloss_rect(draw, box, level):
    draw.rectangle(tuple(int(round(v)) for v in box), fill=int(level))


def _strip_geom(strip, size):
    gutter = max(1, int(round(atlas.GUTTER_PX * (size / 2048.0))))
    y0, y1 = strip["px"]
    ppm_x = size / float(strip["world_w_m"])
    ppm_y = (y1 - y0 - 2 * gutter) / float(strip["world_h_m"])
    return y0, y1, gutter, ppm_x, ppm_y


def paint_wall_openings(albedo, gloss_draw, strip, family, flavor, group,
                        page, palette, pattern, sprites, sources, seed,
                        size, ground=False):
    rng = random.Random(stable_u32(seed, flavor, group, page, family,
                                   strip["px"][0], "openings"))
    y0, y1, gutter, ppm_x, ppm_y = _strip_geom(strip, size)
    base_y = y1 - gutter
    n = max(2, int(round(float(strip["world_w_m"])
                         / float(pattern["period"]))))
    door_slot = rng.randrange(n) if ground else -1
    sill_y = base_y - int(round(float(pattern.get("sill_m", 0.9)) * ppm_y))
    win_w = float(pattern["window_w"]) * ppm_x
    win_h = float(pattern["window_h"]) * ppm_y
    frame_glass = avg_color(palette.get("frame", (220, 220, 220)),
                            palette.get("glass", (96, 112, 126)),
                            palette.get("glass", (96, 112, 126)))
    door_tint = tuple(int(v) for v in rng.choice(
        palette.get("door_pool", ((100, 80, 60),))))
    win_base = window_sprite_base(pattern, flavor, group, sprites)
    win_sprite = sprites[(win_base, flavor, group)]
    barred_sprite = win_base == "window_barred"
    jitter = float(pattern.get("win_jitter", 0.0))
    for i in range(n):
        cx = (i + 0.5) * size / n
        if i == door_slot:
            dw = float(pattern.get("door_w", 1.0)) * ppm_x
            dh = float(pattern.get("door_h", 2.15)) * ppm_y
            box = (cx - dw / 2, base_y - dh, cx + dw / 2, base_y)
            paste_sprite(
                albedo,
                sprites[(door_sprite_base(pattern, flavor, group, sprites),
                         flavor, group)],
                box, door_tint, 0.40, SPRITE_SOFTEN)
            add_gloss_rect(gloss_draw, box, atlas.GLOSS_DOOR)
        else:
            jw = win_w * rng.uniform(1.0 - jitter, 1.0 + jitter)
            jh = win_h * rng.uniform(1.0 - jitter, 1.0 + jitter)
            box = (cx - jw / 2, sill_y - jh, cx + jw / 2, sill_y)
            paste_sprite(albedo, win_sprite, box, frame_glass, 0.40,
                         SPRITE_SOFTEN)
            x0b, wy0, x1b, wy1 = box
            gw, gh = x1b - x0b, wy1 - wy0
            darken_glass(albedo,
                         (x0b + 0.18 * gw, wy0 + 0.12 * gh,
                          x1b - 0.18 * gw, wy1 - 0.12 * gh),
                         dark_glass_color(palette), GLASS_OVERLAY_ALPHA)
            add_gloss_rect(gloss_draw,
                           (x0b + 0.18 * gw, wy0 + 0.12 * gh,
                            x1b - 0.18 * gw, wy1 - 0.12 * gh),
                           atlas.GLOSS_GLASS)
            if (not barred_sprite
                    and rng.random() < float(pattern.get("bars_prob", 0.0))):
                draw = ImageDraw.Draw(albedo)
                bar = (38, 40, 42, 190)
                for frac in (0.25, 0.5, 0.75):
                    sx = int(round(x0b + frac * gw))
                    draw.line((sx, int(wy0), sx, int(wy1)), fill=bar, width=1)
                draw.line((int(x0b), int((wy0 + wy1) / 2), int(x1b),
                           int((wy0 + wy1) / 2)), fill=bar, width=1)
            if rng.random() < float(pattern.get("ac_prob", 0.0)):
                acw = 0.52 * ppm_x
                ach = 0.34 * ppm_y
                ax1 = min(size - 1, x1b)
                ay0 = min(y1 - gutter - ach,
                          wy1 + max(2, int(0.06 * ppm_y)))
                ac_box = (ax1 - acw, ay0, ax1, ay0 + ach)
                if ("ac_unit", flavor, group) in sprites:
                    paste_sprite(albedo, sprites[("ac_unit", flavor, group)],
                                 ac_box, None, 0.0, SPRITE_SOFTEN)
                else:
                    draw = ImageDraw.Draw(albedo)
                    draw.rectangle(tuple(int(round(v)) for v in ac_box),
                                   fill=(178, 180, 181, 210),
                                   outline=(118, 120, 122, 220))


def paint_curtain_overlay(albedo, gloss_draw, strip, palette, pattern,
                          flavor, group, page, seed, size, shade):
    """Spandrel band + slab shadow over the tiled curtain-wall photo."""
    rng = random.Random(stable_u32(seed, flavor, group, page, "curtain",
                                   strip["px"][0]))
    y0, y1, gutter, _ppm_x, ppm_y = _strip_geom(strip, size)
    base_y = y1 - gutter
    fam = palette.get("curtain") or ((88, 104, 118),)
    tint = fam[min(shade, len(fam) - 1)]
    spandrel_h = int(0.9 * ppm_y)
    draw = ImageDraw.Draw(albedo)
    spandrel = tuple(int(max(0, min(255, c - 26))) for c in tint) + (255,)
    draw.rectangle((0, base_y - spandrel_h, size - 1, y1 - 1), fill=spandrel)
    draw.line((0, base_y - spandrel_h + max(2, spandrel_h // 3),
               size, base_y - spandrel_h + max(2, spandrel_h // 3)),
              fill=tuple(max(0, c - 40) for c in tint[:3]) + (255,), width=1)
    darken_glass(albedo, (0, y0 + gutter, size, base_y - spandrel_h),
                 dark_glass_color(palette), CURTAIN_OVERLAY_ALPHA)
    add_gloss_rect(gloss_draw, (0, y0 + gutter, size - 1,
                                base_y - spandrel_h - 1), atlas.GLOSS_GLASS)
    add_gloss_rect(gloss_draw, (0, base_y - spandrel_h, size - 1, y1 - 1), 40)
    _ = rng  # deterministic overlay; rng reserved for future variation


def paint_storefront(albedo, gloss_draw, strip, palette, pattern, sprites,
                     sources, flavor, group, page, seed, size,
                     variant_b=False):
    rng = random.Random(stable_u32(seed, flavor, group, page, "storefront",
                                   strip["px"][0], variant_b))
    y0, y1, gutter, ppm_x, _ppm_y = _strip_geom(strip, size)
    top, bottom = y0 + gutter, y1 - gutter
    n_bays = max(3, int(round(float(strip["world_w_m"])
                              / (4.0 if variant_b else 5.0))))
    tint = avg_color(
        palette.get("glass", (92, 106, 118)),
        rng.choice(palette.get("sign_pool", ((120, 96, 72),))),
        rng.choice(palette.get("awning_pool", ((120, 110, 100),))))
    sprite = sprites[("storefront", flavor, group)]
    bay_w = size // n_bays
    for b in range(n_bays):
        x0 = int(round(b * size / n_bays))
        x1 = int(round((b + 1) * size / n_bays))
        bay_tint = tint if not variant_b else avg_color(
            tint, rng.choice(palette.get("sign_pool", ((120, 96, 72),))))
        paste_sprite(albedo, sprite, (x0, top, x1, bottom), bay_tint, 0.22,
                     SPRITE_SOFTEN)
        h = bottom - top
        add_gloss_rect(gloss_draw, (x0, top, x1, top + h * 0.18),
                       atlas.GLOSS_SIGN)
        add_gloss_rect(gloss_draw, (x0, top + h * 0.18, x1, top + h * 0.31),
                       atlas.GLOSS_AWNING)
        darken_glass(albedo, (x0 + 0.08 * bay_w, top + h * 0.32,
                              x1 - 0.08 * bay_w, bottom),
                     dark_glass_color(palette), STOREFRONT_OVERLAY_ALPHA)
        add_gloss_rect(gloss_draw, (x0 + 0.08 * bay_w, top + h * 0.32,
                                    x1 - 0.08 * bay_w, bottom),
                       atlas.GLOSS_GLASS)
        if pattern.get("awning_stripes") and not variant_b:
            draw = ImageDraw.Draw(albedo)
            stripe_w = max(6, bay_w // 14)
            sy0, sy1 = int(top + h * 0.18), int(top + h * 0.31)
            for sx in range(x0, x1, stripe_w * 2):
                draw.rectangle((sx, sy0, min(sx + stripe_w, x1), sy1),
                               fill=(235, 230, 218, 135))


def paint_lobby(albedo, gloss_draw, strip, palette, pattern, sprites,
                flavor, group, page, seed, size):
    """Entrance band: glazing bays + entrance sprite + canopy line."""
    rng = random.Random(stable_u32(seed, flavor, group, page, "lobby",
                                   strip["px"][0]))
    y0, y1, gutter, ppm_x, ppm_y = _strip_geom(strip, size)
    top, bottom = y0 + gutter, y1 - gutter
    lobby = palette.get("lobby", (66, 74, 82))
    draw = ImageDraw.Draw(albedo)
    n_bays = max(4, int(round(float(strip["world_w_m"]) / 5.0)))
    entrance = sprites.get(("entrance_apt", flavor, group))
    glazing = sprites.get(("window_office", flavor, group))
    door_bay = rng.randrange(n_bays)
    canopy_y = top + int(0.5 * ppm_y)
    for b in range(n_bays):
        x0 = int(round(b * size / n_bays))
        x1 = int(round((b + 1) * size / n_bays))
        pier = max(2, int(0.35 * ppm_x))
        gx0, gx1 = x0 + pier, x1 - pier
        if gx1 <= gx0:
            continue
        if b == door_bay and entrance is not None:
            paste_sprite(albedo, entrance, (gx0, top, gx1, bottom),
                         lobby, 0.18, SPRITE_SOFTEN)
            darken_glass(albedo, (gx0, top, gx1, bottom),
                         dark_glass_color(palette), LOBBY_OVERLAY_ALPHA)
            add_gloss_rect(gloss_draw, (gx0, top, gx1, bottom),
                           atlas.GLOSS_DOOR_GLASS)
        elif glazing is not None:
            paste_sprite(albedo, glazing, (gx0, canopy_y + 2, gx1, bottom),
                         lobby, 0.25, SPRITE_SOFTEN)
            darken_glass(albedo, (gx0, canopy_y + 2, gx1, bottom),
                         dark_glass_color(palette), LOBBY_OVERLAY_ALPHA)
            add_gloss_rect(gloss_draw, (gx0, canopy_y + 2, gx1, bottom),
                           atlas.GLOSS_GLASS)
        else:
            # Painted glazing fallback until the sprite exists.
            grad_top = tuple(min(255, c + 16) for c in lobby) + (255,)
            draw.rectangle((gx0, canopy_y + 2, gx1, bottom), fill=grad_top)
            add_gloss_rect(gloss_draw, (gx0, canopy_y + 2, gx1, bottom),
                           atlas.GLOSS_GLASS)
    # Canopy: deterministic full-width band.
    canopy_h = max(2, int(0.12 * ppm_y))
    draw.rectangle((0, canopy_y - canopy_h, size - 1, canopy_y),
                   fill=(58, 58, 58, 255))
    draw.line((0, canopy_y + 1, size, canopy_y + 1),
              fill=(150, 150, 150, 255), width=1)


def paint_roller(albedo, gloss_draw, strip, palette, pattern, sprites,
                 flavor, group, page, seed, size, dock=False):
    rng = random.Random(stable_u32(seed, flavor, group, page, "roller",
                                   strip["px"][0], dock))
    y0, y1, gutter, ppm_x, ppm_y = _strip_geom(strip, size)
    bottom = y1 - gutter
    door_w_m = float(pattern.get("door_w", 3.4))
    door_h_m = float(pattern.get("door_h", 3.2))
    period = max(door_w_m + 0.8, float(pattern.get("period", 4.0)))
    n = max(3, int(round(float(strip["world_w_m"]) / period)))
    door_w = int(round(door_w_m * ppm_x))
    top = max(y0 + gutter, int(round(bottom - door_h_m * ppm_y)))
    tint = avg_color(palette_color(palette, "concrete", 1),
                     palette.get("roof_metal", (130, 134, 138)))
    base = "dock_door" if dock and ("dock_door", flavor, group) in sprites \
        else "roller_door"
    sprite = sprites[(base, flavor, group)]
    for i in range(n):
        cell_x = int(round(i * size / n))
        gap = int(round(0.3 * ppm_x))
        x0 = cell_x + gap
        x1 = min(size, x0 + door_w)
        paste_sprite(albedo, sprite, (x0, top, x1, bottom), tint, 0.26,
                     SPRITE_SOFTEN)
        add_gloss_rect(gloss_draw, (x0, top, x1, bottom),
                       atlas.GLOSS_ROLLER_DOOR)
        if rng.random() < 0.25:
            draw = ImageDraw.Draw(albedo)
            draw.rectangle((x0, bottom - 8, x1, bottom),
                           fill=(45, 44, 42, 90))


def paint_balcony_band(albedo, gloss_draw, strip, palette, pattern, sprites,
                       flavor, group, page, seed, size):
    """Balcony front band: shadowed interior + tiled regional rail sprite."""
    rng = random.Random(stable_u32(seed, flavor, group, page, "balcony",
                                   strip["px"][0]))
    y0, y1, gutter, ppm_x, _ppm_y = _strip_geom(strip, size)
    draw = ImageDraw.Draw(albedo)
    draw.rectangle((0, y0, size - 1, y1 - 1), fill=(44, 46, 48, 255))
    rail = sprites.get(("balcony_rail", flavor, group))
    panel = palette.get("balcony", (150, 148, 145))
    if rail is not None:
        unit_w = int(round(2.0 * ppm_x))
        for x0 in range(0, size, unit_w):
            paste_sprite(albedo, rail,
                         (x0, y0 + gutter, min(size, x0 + unit_w),
                          y1 - gutter),
                         panel, 0.3, SPRITE_SOFTEN)
    else:
        # Painted fallback: solid per-unit panels with a top rail.
        n_units = max(2, int(round(float(strip["world_w_m"]) / 2.0)))
        for i in range(n_units):
            xa = int(round(i * size / n_units))
            xb = int(round((i + 1) * size / n_units)) - 2
            tone = tuple(max(0, min(255, c + rng.randint(-8, 8)))
                         for c in panel)
            draw.rectangle((xa, y0 + gutter + 4, xb, y1 - gutter - 2),
                           fill=tone + (255,))
        draw.rectangle((0, y0 + gutter, size - 1, y0 + gutter + 3),
                       fill=tuple(panel) + (255,))
    add_gloss_rect(gloss_draw, (0, y0, size - 1, y1 - 1), 20)
    _ = rng


def paint_highband(albedo, gloss_draw, strip, palette, pattern, sprites,
                   flavor, group, page, seed, size):
    """Industrial high-level glazing band: tiled window_ind sprite."""
    rng = random.Random(stable_u32(seed, flavor, group, page, "highband",
                                   strip["px"][0]))
    y0, y1, gutter, ppm_x, _ppm_y = _strip_geom(strip, size)
    glass = palette.get("glass", (96, 112, 126))
    sprite = sprites.get(("window_ind", flavor, group))
    top, bottom = y0 + gutter, y1 - gutter
    if sprite is not None:
        unit_w = int(round(3.0 * ppm_x))
        for x0 in range(0, size, unit_w):
            paste_sprite(albedo, sprite,
                         (x0, top, min(size, x0 + unit_w), bottom),
                         glass, 0.3, SPRITE_SOFTEN)
    else:
        draw = ImageDraw.Draw(albedo)
        n_panes = max(12, int(round(float(strip["world_w_m"]) / 0.9)))
        for i in range(n_panes):
            xa = int(round(i * size / n_panes)) + 1
            xb = int(round((i + 1) * size / n_panes)) - 1
            tone = tuple(max(0, min(255, c + rng.randint(-10, 10)))
                         for c in glass)
            draw.rectangle((xa, top + 2, xb, bottom - 2), fill=tone + (255,))
    darken_glass(albedo, (0, top, size, bottom),
                 dark_glass_color(palette), HIGHBAND_OVERLAY_ALPHA)
    add_gloss_rect(gloss_draw, (0, top, size - 1, bottom),
                   atlas.GLOSS_GLASS - 30)


def stabilize_band_edges(arr, y0, y1, gutter):
    band = arr[y0:y1].astype(np.float32)
    if band.shape[0] <= 2 * gutter + 4:
        interior = band.reshape(-1, 3).mean(axis=0)
    else:
        interior = band[gutter:-gutter].reshape(-1, 3).mean(axis=0)
    band[:2] = interior
    band[-2:] = interior
    for k in range(2, min(8, band.shape[0] // 2)):
        t = (k - 1) / 7.0
        band[k] = band[k] * t + interior * (1.0 - t)
        band[-k - 1] = band[-k - 1] * t + interior * (1.0 - t)
    band[:, -1, :] = band[:, 0, :]
    arr[y0:y1] = np.clip(np.rint(band), 0, 255).astype(np.uint8)


def stabilize_row_chroma(arr, y0, y1, strength=0.9):
    band = arr[y0:y1].astype(np.float32)
    if band.size == 0:
        return
    rg = band[..., 0] - band[..., 1]
    bg = band[..., 2] - band[..., 1]
    row_rg = rg.mean(axis=1)
    row_bg = bg.mean(axis=1)
    band[..., 0] += (float(rg.mean()) - row_rg)[:, None] * strength
    band[..., 2] += (float(bg.mean()) - row_bg)[:, None] * strength
    arr[y0:y1] = np.clip(np.rint(band), 0, 255).astype(np.uint8)


def base_gloss_for_strip(name, kind, pattern):
    if kind == "roof":
        if name == "roof_tile":
            return (atlas.GLOSS_BASE["roof_tile_glazed"]
                    if pattern.get("tile_gloss")
                    else atlas.GLOSS_BASE["roof_tile"])
        return atlas.GLOSS_BASE.get(name, atlas.GLOSS_BASE["wall"])
    return atlas.GLOSS_BASE.get(kind, atlas.GLOSS_BASE["wall"])


def strip_family(name, kind):
    """(family, shade_index) for a strip name."""
    shade_map = {"a": 0, "b": 1, "c": 2}
    if kind in ("wall", "glass", "plain"):
        parts = name.split("_")
        family = parts[1]
        shade = shade_map.get(parts[2], 0) if len(parts) > 2 else 0
        return family, shade
    if kind == "ground":
        return name.split("_")[1], 0
    if kind in ("storefront", "roller", "lobby", "balcony", "highband"):
        return "concrete", 0
    if kind == "trim":
        return "trim", 0
    return name, 0


def material_base_for(name, kind, family, group, flavor, shade,
                      sources: Sources):
    """Source base for a strip's underlying material photo."""
    if kind == "roof":
        return MATERIAL_SOURCES.get(name, "roof_flat")
    if kind == "trim":
        return "trim_wood"
    if family == "curtain":
        if shade == 1 and sources.has("curtain_wall_dark"):
            return "curtain_wall_dark"
        return "curtain_wall"
    if family == "panel" and shade == 1 and flavor == "asia" \
            and sources.has("mosaic_wall", flavor, group):
        return "mosaic_wall"
    override = GROUP_MATERIAL_OVERRIDES.get((group, family))
    if override:
        for base in override:
            if sources.has(base, flavor, group):
                return base
    return MATERIAL_SOURCES.get(family, "concrete_wall")


def compose_page(flavor, group, page, sub_layout, references, sources,
                 sprites, seed):
    size = int(sub_layout["size"])
    palette = atlas.combo_page_palette(flavor, group, page)
    pattern = atlas.pattern_for_combo(flavor, group, references, page)
    img = Image.new("RGBA", (size, size), (128, 128, 128, 255))
    gloss = Image.new("L", (size, size), atlas.GLOSS_BASE["wall"])
    gloss_draw = ImageDraw.Draw(gloss)
    gutter = max(1, int(round(atlas.GUTTER_PX * (size / 2048.0))))

    # curtain_wall_dark spans like curtain_wall.
    SOURCE_SPAN_Y_M.setdefault("curtain_wall_dark", 3.2)
    MATERIAL_CONTRAST.setdefault("curtain_wall_dark", 0.60)
    SHIFT_REPEATS.setdefault("curtain_wall_dark", False)

    for name, strip in sorted(sub_layout["strips"].items(),
                              key=lambda item: item[1]["px"][0]):
        kind = strip["kind"]
        y0, y1 = strip["px"]
        family, shade = strip_family(name, kind)
        mat_base = material_base_for(name, kind, family, group, flavor,
                                     shade, sources)
        src, span_base, regional = sources.get_material(mat_base, flavor,
                                                        group)
        if kind == "roof":
            target = palette_color(palette, name, 0)
        elif family == "trim":
            target = palette_color(palette, "trim", 0)
        elif family in palette:
            target = palette_color(palette, family, shade)
        else:
            target = palette_color(palette, "concrete", shade)
        rng = random.Random(stable_u32(seed, flavor, group, page, name,
                                       "material"))
        band = tile_material(src, strip, span_base, size, target, rng,
                             regional, flavor)
        band = apply_unit_banding(band, strip, family, palette, pattern,
                                  rng, regional, size)
        grime_base = float(pattern.get("grime", 0.0))
        if page == 1:
            grunge_strength = 0.28 + grime_base * 0.22
        elif page == 2:
            grunge_strength = 0.04 + grime_base * 0.04
            band = np.clip(band * 1.04 + 3.0, 0, 255)
        else:
            grunge_strength = 0.10 + grime_base * 0.08
        if kind in ("roof", "trim", "glass"):
            grunge_strength *= 0.35
        grunge_strength *= float(
            (FLAVOR_DIRT.get(flavor) or {}).get("grunge_scale", 1.0))
        if flavor in CLEAN_FLAVORS:
            # Clean flavors NEVER get the grunge overlay: the page-1
            # formula has a constant 0.28 floor even at grime=0, which is
            # exactly how asia grime kept coming back.
            grunge_strength = 0.0
        band = apply_grunge(band, sources.images["grunge"], grunge_strength,
                            rng)
        # Row-chroma stabilization BEFORE sprites (post-sprite runs paint
        # broad chroma zones across window/sill lines).
        band_u8 = np.clip(np.rint(band), 0, 255).astype(np.uint8)
        stabilize_row_chroma(band_u8, 0, band_u8.shape[0], 0.92)
        img.alpha_composite(
            Image.fromarray(band_u8, "RGB").convert("RGBA"), (0, y0))
        add_gloss_rect(gloss_draw, (0, y0, size - 1, y1 - 1),
                       base_gloss_for_strip(name, kind, pattern))

        if kind == "wall":
            paint_wall_openings(img, gloss_draw, strip, family, flavor,
                                group, page, palette, pattern, sprites,
                                sources, seed, size)
        elif kind == "glass":
            paint_curtain_overlay(img, gloss_draw, strip, palette, pattern,
                                  flavor, group, page, seed, size, shade)
        elif kind == "ground":
            paint_wall_openings(img, gloss_draw, strip, family, flavor,
                                group, page, palette, pattern, sprites,
                                sources, seed, size, ground=True)
        elif kind == "storefront":
            paint_storefront(img, gloss_draw, strip, palette, pattern,
                             sprites, sources, flavor, group, page, seed,
                             size, variant_b=name.endswith("_b"))
        elif kind == "lobby":
            paint_lobby(img, gloss_draw, strip, palette, pattern, sprites,
                        flavor, group, page, seed, size)
        elif kind == "roller":
            paint_roller(img, gloss_draw, strip, palette, pattern, sprites,
                         flavor, group, page, seed, size,
                         dock=name.endswith("_dock"))
        elif kind == "balcony":
            paint_balcony_band(img, gloss_draw, strip, palette, pattern,
                               sprites, flavor, group, page, seed, size)
        elif kind == "highband":
            paint_highband(img, gloss_draw, strip, palette, pattern,
                           sprites, flavor, group, page, seed, size)

    rgb = np.asarray(img.convert("RGB"), dtype=np.uint8).copy()
    for strip in sub_layout["strips"].values():
        stabilize_band_edges(rgb, int(strip["px"][0]), int(strip["px"][1]),
                             gutter)
    return Image.fromarray(rgb, "RGB"), gloss


def compose(output: Path, sources_dir: Path, combos, layout_path: Path,
            pages: int, seed: int) -> None:
    with layout_path.open("r", encoding="utf-8") as fh:
        layout = json.load(fh)
    if int(layout.get("version", 1)) < 2:
        raise SystemExit("atlas_layout.json is pre-overhaul; run atlas.py")
    references = atlas._load_reference_styles()
    sources = Sources(sources_dir)
    sprites = build_sprites(sources)
    textures = output / "textures"
    textures.mkdir(parents=True, exist_ok=True)
    for key in combos:
        flavor, group = key.split("/")
        sub = layout["combos"][key]
        for page in range(pages):
            print(f"compositing {key} page {page + 1}/{pages}", flush=True)
            albedo, gloss = compose_page(flavor, group, page, sub,
                                         references, sources, sprites, seed)
            name = atlas.texture_name(flavor, group, page)
            # Adaptive-palette save: full 4096 res at ~1-2 MB on disk.
            albedo.quantize(
                colors=QUANT_COLORS, method=Image.Quantize.FASTOCTREE,
            ).save(textures / name, optimize=True)
            normal = atlas.build_normal_map(gloss, NML_SIZE)
            normal.save(textures / f"{name[:-4]}_nml.png", compress_level=6)


def main(argv=None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--output", required=True,
                        help="Library package folder; PNGs land in textures/.")
    parser.add_argument("--sources", default=str(DEFAULT_SOURCES))
    parser.add_argument("--layout",
                        default=str(HERE / "atlas_layout.json"))
    parser.add_argument("--combos", default=None,
                        help="Comma-separated flavor/group keys "
                             "(default: all 32).")
    parser.add_argument("--pages", type=int, default=3)
    parser.add_argument("--seed", type=int, default=101)
    args = parser.parse_args(argv)
    if args.combos:
        combos = [c.strip() for c in args.combos.split(",") if c.strip()]
    else:
        combos = [combo_key(f, g) for f in FLAVORS for g in GROUPS]
    compose(Path(args.output), Path(args.sources), combos,
            Path(args.layout), max(1, args.pages), args.seed)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
